services:
  postgres:
    ports: !override []

  redis:
    ports: !override []

  api:
    ports: !override
      - "10.10.1.2:8000:8000"

  web:
    ports: !override
      - "10.10.1.2:3000:3000"

  reverse-proxy:
    ports: !override []
